import fs from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const repoRoot = path.resolve(__dirname, "..");

const sourceFiles = [
  "styles/00-fonts.css",
  "styles/00-foundation.css",
  "styles/01-hero.css",
  "styles/02-content.css",
  "styles/03-editor.css",
  "styles/04-forms.css",
  "styles/05-graph-wiki.css",
  "styles/05-map.css",
  "styles/06-workspace.css",
  "styles/07-overlays-comments.css",
  "styles/08-responsive.css"
];

export async function buildStylesBundle() {
  const parts = await Promise.all(
    sourceFiles.map(async (relativePath) => {
      const absolutePath = path.join(repoRoot, relativePath);
      const content = await fs.readFile(absolutePath, "utf8");
      const normalized = relativePath === "styles/00-fonts.css"
        ? content.replaceAll('url("./fonts/', 'url("./styles/fonts/')
        : content;
      return `/* ${relativePath} */\n${normalized.trimEnd()}\n`;
    })
  );

  return `/* Generated by tooling/build-styles.mjs. Edit files in /styles and rebuild. */\n\n${parts.join("\n")}`;
}

export async function writeBundledStyles(outputPath = path.join(repoRoot, "dist", "styles.css")) {
  const output = await buildStylesBundle();
  await fs.mkdir(path.dirname(outputPath), { recursive: true });
  await fs.writeFile(outputPath, output, "utf8");
  return outputPath;
}

if (path.resolve(process.argv[1] || "") === __filename) {
  await writeBundledStyles();
}
